# Generated by Django 6.0.3 on 2026-04-05 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('tools', 'Tools'), ('language', 'Language'), ('other', 'Other')], default='other', max_length=50)),
                ('level', models.IntegerField(default=80, help_text='Skill level from 0 to 100')),
                ('icon', models.CharField(blank=True, help_text='Emoji icon e.g. ⚛️', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
